# TRADUCCION DE LA BIBLIOTECA BASE
#
msgid ""
msgstr ""
"Project-Id-Version: 0.0.1\n"
"POT-Creation-Date: 2020-01-01 00:00-0300\n"
"PO-Revision-Date: 2024-05-18 01:20-0300\n"
"Last-Translator: \n"
"Language-Team: \n"
"Language: es\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: web_flask.py:1
msgid "Los-datos-recibidos-no-se-procesaron"
msgstr "Los datos recibidos no fueron procesados correctamente"

#: web_flask.py:2
msgid "Error-no-manejado"
msgstr "Error interno del Servidor"

#: web_flask.py:3
msgid "API-key-invalida"
msgstr "API key no válida"

#: web_flask.py:4
msgid "Encabezado-de-autorizacion-invalido"
msgstr "Encabezado de autorización no válido"

#: web_flask.py:5
msgid "Token-invalido"
msgstr "Token no válido o caducado"

#: servicio.py:1
msgid "No-autorizado-para-acceder"
msgstr "No tiene permisos para realizar esta acción"

#: web_fastapi.py:1
msgid "Los-datos-recibidos-son-invalidos"
msgstr "Los datos recibidos no son válidos"

#: exportador_word.py:1
msgid "Error-en-exportador-Word"
msgstr "Error en exportador Word"

#: exportador_pdf.py:1
msgid "Error-en-exportador-PDF"
msgstr "Error en exportador PDF"

#: exportador_excel.py:1
msgid "Error-en-exportador-Excel"
msgstr "Error en exportador Excel"

#: exportador_csv.py:1
msgid "Error-en-exportador-CSV"
msgstr "Error en exportador CSV"

#: web.py:1
msgid "El-archivo-ya-existe"
msgstr "Ya existe un archivo llamado {nombre}"

#: web.py:2
msgid "Error-al-guardar-el-archivo"
msgstr "Error al guardar el archivo"

#: adaptadores.py:1
msgid "Archivo-cargado-con-exito"
msgstr "El archivo fue cargado con éxito"

#: web_fastapi.py:2
msgid "Tipo-de-carga-no-valido"
msgstr "Tipo de carga no válido"

#: web_flask.py:6
msgid "No-se-recibio-ninguna-carga"
msgstr "No se recibió ninguna carga"

#: dominio.py:1
msgid "La-carga-recibida-no-contiene-archivo"
msgstr "La carga recibida no contiene archivo"

#: dominio.py:2
msgid "El-tipo-de-archivo-no-esta-permitido"
msgstr "El tipo de archivo no está permitido"

#: dominio.py:3
msgid "El-archivo-supera-el-peso-maximo-aceptado"
msgstr "El archivo supera el peso máximo aceptado"

#: disco_local.py:1
msgid "Archivo-no-encontrado"
msgstr "El archivo no fue encontrado"

#: disco_local.py:2
msgid "Permiso-denegado-para-eliminar-el-archivo"
msgstr "Permiso denegado para eliminar el archivo"

#: disco_local.py:3
msgid "Error-desconocido-al-acceder-al-archivo"
msgstr "Error desconocido al acceder al archivo"

#: disco_local.py:4
msgid "Permiso-denegado-para-escribir-el-archivo"
msgstr "Permiso denegado para escribir el archivo"

#: disco_local.py:5
msgid "Permiso-denegado-para-abrir-el-archivo"
msgstr "Permiso denegado para abrir el archivo"

#: disco_local.py:6
msgid "Error-de-IO-al-escribir-el-archivo"
msgstr "Error de I/O al escribir en el archivo"

#: disco_local.py:7
msgid "La-carpeta-no-existe"
msgstr "La carpeta no existe"

#: disco_local.py:8
msgid "Permiso-denegado-para-eliminar-la-carpeta"
msgstr "Permiso denegado para eliminar la carpeta"

#: disco_local.py:9
msgid "Error-del-sistema-operativo-al-eliminar-la-carpeta"
msgstr "Error del sistema operativo al eliminar la carpeta"

#: disco_local.py:10
msgid "Permiso-denegado-para-crear-la-carpeta"
msgstr "Permiso denegado para crear la carpeta"

#: disco_local.py:11
msgid "Error-del-sistema-operativo-al-crear-la-carpeta"
msgstr "Error del sistema operativo al crear la carpeta"

#: disco_local.py:12
msgid "Error-desconocido-al-acceder-a-la-carpeta"
msgstr "Error desconocido al acceder a la carpeta"

